###################################################
# BUILT-IN CONFIGURATION OPTOINS                  #
# https://gohugo.io/getting-started/configuration #
###################################################

baseURL = "https://basilpapadimas.github.io/website/" # website root path
enableRobotsTXT = true             # /robots.txt
languageCode = "en"                # content language
paginate = 5                       # number of posts each page
rssLimit = 10                      # maximum items in rss feeds
theme = "hugo-theme-texify"        # theme directory name
title = "Basil Papadimas"                   # website title

[author]
email = "papadimas@protonmail.com" # your email
name = "Basil Papadimas"          # your name

# https://gohugo.io/getting-started/configuration-markup
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true # enable html in markdown
[markup.highlight]
style = "emacs" # syntax highlight style, see https://xyproto.github.io/splash/docs/

# https://gohugo.io/content-management/menus/
[[menu.main]]
identifier = "about"
name = "About"
url = "/"
weight = 1
[[menu.main]]
identifier = "archives"
name = "Blog"
url = "/posts/"
weight = 2

# https://gohugo.io/content-management/taxonomies#configure-taxonomies
[taxonomies]
series = "series" # see https://gohugo.io/templates/internal/#open-graph
tags = "tags"


########################
# TEXIFY THEME OPTIONS #
########################

[params]
description = "Basil Papadimas' homepage" # website description
favicon = "favicon.ico" # path to website icon, relative to ./static
footnote = """
with <a class=link href=https://web.archive.org/web/20170831062341/https://scobberlotcher.net/ target=_blank rel=noopener>cats</a>!
"""
keywords = ["papadimas", "homepage", "athens", "greece","programming", "mathematics", "physics"] # website keywords

customCSS = []            # path to custom css files, relative to ./static
customJS = []             # path to custom js files, relative to ./static
dateFormat = "2006-01-02" # date format, see https://gohugo.io/functions/format/
fullTextRSS = true        # output full-text (instead of only summary) rss
since = "2017"            # website created year
toc = false               # whether to enable table of contents in posts

[params.math]
enable = false # whether to enable math typesetting
use = "katex"  # katex or mathjax

[params.outdated]
enable = false # whether to display warnings for outdated posts
limit = 1000   # days between last modified time and outdated time
# warning to be displayed
warning = "⚠️ It has been <i>%d</i> days since the last update, the content of the article may be outdated."

